services:
  db:
    image: postgres:latest  
    container_name: postgres_oresto 
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./app/models/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./app/models/seeding.sql:/docker-entrypoint-initdb.d/seeding.sql 
  api:
    build: "."   
    container_name: oresto_api
    restart: always
    depends_on:
      - db
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules .
    command: [ "sh", "-c", "sleep 5 && node app/models/seed.js && npm start" ]
volumes:
  pgdata:
