services:
  db:
    image: postgres:latest  # ✅ Correction ici
    container_name: postgres_oresto  # ✅ Correction ici
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./app/models/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build: "."   # ✅ Garde les guillemets pour éviter des erreurs de parsing
    container_name: oresto_api
    restart: always
    depends_on:
      - db
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules  # ✅ Correction de l'indentation

volumes:
  pgdata:
